version: '3'

services:
  apache:
    image: httpd:2.4
    container_name: apache
    volumes:
      - ./src:/usr/local/apache2/htdocs

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache 
    restart: always
